query About {
	about {
		id
		text {
			blocks
			value
			links
		}
		audio {
			...AudioFragment
		}
	}
	introduction {
		text {
			blocks
			value
			links
		}
		audio {
			...AudioFragment
		}
	}
}
