query AllPosts($first: IntType = 100, $skip: IntType = 0) {
	allImages(first: $first, skip: $skip, orderBy: _firstPublishedAt_DESC) {
		...ImagePostFragment
	}
	_allImagesMeta {
		count
	}
	allTexts(first: $first, skip: $skip, orderBy: _firstPublishedAt_DESC) {
		...TextPostFragment
	}
	_allTextsMeta {
		count
	}
}

query Post($slug: String) {
	image(filter: { slug: { eq: $slug } }) {
		...ImagePostFragment
	}
	text(filter: { slug: { eq: $slug } }) {
		...TextPostFragment
	}
}

fragment ImagePostFragment on ImageRecord {
	__typename
	_firstPublishedAt
	id
	image {
		...ImageFragment
	}
	audio {
		...AudioFragment
	}
	textToVoice
	background {
		hex
	}
	colorBackground {
		hex
	}
	slug
}

fragment TextPostFragment on TextRecord {
	__typename
	_firstPublishedAt
	id
	title
	text {
		blocks
		links
		value
	}
	textColor {
		hex
	}
	backgroundColor {
		hex
	}
	audio {
		...AudioFragment
	}
	narrow
	slug
}
