query AllPosts($first: IntType = 100, $skip: IntType = 0) {
	allImages(first: $first, skip: $skip, orderBy: _firstPublishedAt_DESC) {
		__typename
		id
		image {
			...ImageFragment
		}
		textToVoice
		background {
			hex
		}
		colorBackground {
			hex
		}
		_firstPublishedAt
	}
	_allImagesMeta {
		count
	}
	allTexts(first: $first, skip: $skip, orderBy: _firstPublishedAt_DESC) {
		__typename
		id
		text {
			blocks
			links
			value
		}
		_firstPublishedAt
	}
	_allTextsMeta {
		count
	}
}
